Repository Star-Academy/Team8-Codes, pull requests merged in 2020-08, with the labels that each got.

#4 Phase03/unittest
  google/.gitignore
  google/App.java
  google/main/resources/input/.gitkeep
  google/main/src/core/apps/SearchEngineApp.java
  google/main/src/core/engine/IndexInterface.java
  google/main/src/core/engine/InvertedIndex.java
  google/main/src/core/query/AndTerms.java
  google/main/src/core/query/ExcTerms.java
  google/main/src/core/query/OrTerms.java
  google/main/src/core/query/Terms.java
  google/main/src/core/structures/Document.java
  google/main/src/core/structures/Entity.java
  google/main/src/core/structures/Token.java
  google/main/src/utils/ConsoleApp.java
  google/main/src/utils/FileHandler.java
  google/main/src/utils/FileHandlerInterface.java
  google/main/src/utils/Prettifier.java
  google/test/resources/input/doc1.txt
  google/test/resources/input/doc2.txt
  google/test/resources/input/doc3.txt
  google/test/src/core/engine/TestEngine.java
  google/test/src/core/engine/TestInvertedIndex.java
  google/test/src/core/query/TestAndTerms.java
  google/test/src/core/query/TestExcTerms.java
  google/test/src/core/query/TestOrTerms.java
  google/test/src/core/query/TestQuery.java
  google/test/src/core/query/TestTerms.java
  google/test/src/core/query/TestTermsAbstract.java
  google/test/src/core/structures/TestDocument.java
  google/test/src/core/structures/TestEntity.java
  google/test/src/core/structures/TestToken.java
  google/test/src/utils/TestFileHandler.java
  google/test/src/utils/TestPrettifier.java
Labels: Phase03

#3 Phase04/csharp
  .gitignore
  School/.gitignore
  School/Program.cs
  School/core/ReportManager.cs
  School/models/Record.cs
  School/models/Student.cs
  School/models/StudentReport.cs
  School/resources/input/.gitkeep
  School/students.csproj
  School/utils/JsonHandler.cs
Labels: Phase04

#5 Phase05/google sharp
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  GoogleSharp/.gitignore
  GoogleSharp/GoogleSharp.Test/GoogleSharp.Test.csproj
  GoogleSharp/GoogleSharp.Test/Tests/src/core/engine/GoogleInvertedIndexTests.cs
  GoogleSharp/GoogleSharp.Test/Tests/src/core/engine/QueryEngineTests.cs
  GoogleSharp/GoogleSharp.Test/Tests/src/core/query/AndTermsTests.cs
  GoogleSharp/GoogleSharp.Test/Tests/src/core/query/ExcTermsTests.cs
  GoogleSharp/GoogleSharp.Test/Tests/src/core/query/OrTermsTests.cs
  GoogleSharp/GoogleSharp.Test/Tests/src/core/query/QueryBuilderTests.cs
  GoogleSharp/GoogleSharp.Test/Tests/src/core/structures/DocumentTests.cs
  GoogleSharp/GoogleSharp.Test/Tests/src/core/structures/TokenTests.cs
  GoogleSharp/GoogleSharp.Test/Tests/src/utils/FileHandlerTests.cs
  GoogleSharp/GoogleSharp.Test/Tests/src/utils/PrettifierTests.cs
  GoogleSharp/GoogleSharp.sln
  GoogleSharp/GoogleSharp/GoogleSharp.csproj
  GoogleSharp/GoogleSharp/src/core/engine/GoogleInvertedIndex.cs
  GoogleSharp/GoogleSharp/src/core/engine/InvertedIndex.cs
  GoogleSharp/GoogleSharp/src/core/engine/QueryEngine.cs
  GoogleSharp/GoogleSharp/src/core/query/AndTerms.cs
  GoogleSharp/GoogleSharp/src/core/query/ExcTerms.cs
  GoogleSharp/GoogleSharp/src/core/query/OrTerms.cs
  GoogleSharp/GoogleSharp/src/core/query/QueryBuilder.cs
  GoogleSharp/GoogleSharp/src/core/query/Terms.cs
  GoogleSharp/GoogleSharp/src/core/structures/Document.cs
  GoogleSharp/GoogleSharp/src/core/structures/Token.cs
  GoogleSharp/GoogleSharp/src/utils/FileHandler.cs
  GoogleSharp/GoogleSharp/src/utils/Prettifier.cs
  School/obj/Debug/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs
  School/obj/Debug/netcoreapp3.1/students.AssemblyInfo.cs
  School/obj/Debug/netcoreapp3.1/students.AssemblyInfoInputs.cache
  School/obj/Debug/netcoreapp3.1/students.assets.cache
  School/obj/Debug/netcoreapp3.1/students.csproj.CopyComplete
  School/obj/Debug/netcoreapp3.1/students.csproj.CoreCompileInputs.cache
  School/obj/Debug/netcoreapp3.1/students.csproj.FileListAbsolute.txt
  School/obj/Debug/netcoreapp3.1/students.csprojAssemblyReference.cache
  School/obj/Debug/netcoreapp3.1/students.dll
  School/obj/Debug/netcoreapp3.1/students.exe
  School/obj/Debug/netcoreapp3.1/students.genruntimeconfig.cache
  School/obj/Debug/netcoreapp3.1/students.pdb
  School/obj/project.assets.json
  School/obj/project.nuget.cache
  School/obj/students.csproj.nuget.dgspec.json
  School/obj/students.csproj.nuget.g.props
  School/obj/students.csproj.nuget.g.targets
  School/resources/input/Records.json
  School/resources/input/Students.json
Labels: Phase05

#7 Phase08/bagherzadeh
  Bagherzadeh/.gitignore
  Bagherzadeh/BagherEngine/App/App.cs
  Bagherzadeh/BagherEngine/App/ConsoleApp.cs
  Bagherzadeh/BagherEngine/App/SearchEngineApp.cs
  Bagherzadeh/BagherEngine/BagherEngine.csproj
  Bagherzadeh/BagherEngine/Elastic/ElasticClientFactory.cs
  Bagherzadeh/BagherEngine/Elastic/Engine.cs
  Bagherzadeh/BagherEngine/Elastic/FieldsDefiner.cs
  Bagherzadeh/BagherEngine/Elastic/Importer.cs
  Bagherzadeh/BagherEngine/Elastic/IndexDefiner.cs
  Bagherzadeh/BagherEngine/Elastic/Validator.cs
  Bagherzadeh/BagherEngine/Exceptions/ElasticApiException.cs
  Bagherzadeh/BagherEngine/Exceptions/ElasticClientException.cs
  Bagherzadeh/BagherEngine/Exceptions/ElasticException.cs
  Bagherzadeh/BagherEngine/Exceptions/ElasticServerException.cs
  Bagherzadeh/BagherEngine/Models/Document.cs
  Bagherzadeh/BagherEngine/Models/Token.cs
  Bagherzadeh/BagherEngine/QuerySystem/AndTerms.cs
  Bagherzadeh/BagherEngine/QuerySystem/ExcTerms.cs
  Bagherzadeh/BagherEngine/QuerySystem/OrTerms.cs
  Bagherzadeh/BagherEngine/QuerySystem/Query.cs
  Bagherzadeh/BagherEngine/QuerySystem/Terms.cs
  Bagherzadeh/BagherEngine/Utils/FileHandler.cs
  Bagherzadeh/BagherEngine/Utils/Prettifier.cs
  Bagherzadeh/Bagherzadeh.sln
  google/.gitignore
  google/App.java
  google/main/src/core/apps/SearchEngineApp.java
  google/main/src/core/engine/Engine.java
  google/main/src/core/engine/IndexInterface.java
  google/main/src/core/engine/InvertedIndex.java
  google/main/src/core/query/AndTerms.java
  google/main/src/core/query/ExcTerms.java
  google/main/src/core/query/OrTerms.java
  google/main/src/core/query/Query.java
  google/main/src/core/query/Terms.java
  google/main/src/core/structures/Document.java
  google/main/src/core/structures/Entity.java
  google/main/src/core/structures/Token.java
  google/main/src/exceptions/.gitkeep
  google/main/src/utils/ConsoleApp.java
  google/main/src/utils/FileHandler.java
  google/main/src/utils/FileHandlerInterface.java
  google/main/src/utils/Prettifier.java
  google/test/resources/input/doc1.txt
  google/test/resources/input/doc2.txt
  google/test/resources/input/doc3.txt
  google/test/src/core/engine/TestEngine.java
  google/test/src/core/engine/TestInvertedIndex.java
  google/test/src/core/query/TestAndTerms.java
  google/test/src/core/query/TestExcTerms.java
  google/test/src/core/query/TestOrTerms.java
  google/test/src/core/query/TestQuery.java
  google/test/src/core/query/TestTermsAbstract.java
  google/test/src/core/structures/TestDocument.java
  google/test/src/core/structures/TestEntity.java
  google/test/src/core/structures/TestToken.java
  google/test/src/utils/TestFileHandler.java
  google/test/src/utils/TestPrettifier.java
Labels: Phase08
